<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800"> Salam Perjuangan <?= $user['name']; ?> !</h1>
    <div class="card mx-auto border-danger shadow" style="width: 60rem;">
        <img src="<?= base_url('assets/img/breadcrumb/') . 'breadcrumb-bg.png' ?>" class="card-img-top" alt="...">
        <div class="card-body">
            <h4 class="card-title text-center fw-bolder" style="font-weight:bold">Menjelajahi Pendirian Serikat Pekerja Kampus</h4>
            <h5 class="text-center fw-bolder">Dhia Al Uyun & Hariati Sinaga</h5>
            <h6 class="text-center fw-bolder">Ketua dan Sekretaris Serikat Pekerja Kampus</h6>
            <br></br>
            <p class="card-text text-justify mx-5 lh-sm"> <i>“Tujuh belas Agustus Tahun Empat Lima, itulah hari kemerdekaan kita…” </i>, lagu ciptaan Husei Mutahar mengingatkan akan pentingnya peringatan kemerdekaan. Ketika memaknai hari kemerdekaan, tentulah pertanyaan yang terpikir, apakah pekerja kampus telah merdeka? Pekerja kampus belum merdeka, kebebasan masih menjadikan mereka ketergantungan dengan pemberi kerja, atau dalam Bahasa Permenpan RB Nomor 1 Tahun 2023 disebut atasan. Atasan ini, dengan berbagai kewajiban administratif yang tidak berbanding lurus dengan penghasilan yang didapat. Tim Riset kesejahteraan dosen telah menemukan bahwa sebanyak 42,9% dosen menerima upah di bawah Rp 3 juta per bulan. Tim Perumusan Masalah Komite Persiapan Pembentukan Serikat Pekerja Kampus juga menemukan bahwa 58% tenaga kependidikan merasa bahwa penghasilannya tidak mencukupi kebutuhan hidup. <br>

            <h5 class="card-text text-justify mx-5 lh-sm"><br class="fw-bolder" style="font-weight:bold">Jalan buntu kesejahteraan</h5><br>

            <p class="card-text text-justify mx-5 lh-sm">Untuk dapat mencukupi hidupnya, banyak pekerja kampus melakukan pekerjaan tambahan, menerima berbagai proyek hingga berkelindan dengan kekuasaan, sehingga marwah keilmuannya terganggu, dan merusak ekosistem pendidikan di lingkungan perguruan tinggi. Hal lainnya yang mendukung situasi ini adalah sistem pendidikan tinggi di Indonesia yang buruk. Dikatakan buruk karena maraknya obral Honoris Causa, Obral Jabatan Profesor, 35% suara kementerian dan kisruh perebutan kuasa rektor, budaya plagiasi, eksploitasi mahasiswa, penundukan dosen oleh kehendak elit politik, free riding penulisan jurnal, formalisme akademisi, investasi elit melalui penunjukan komisaris dari kalangan akademisi, korupsi, kolusi dan nepotisme, jual beli nilai dan permainan joki kampus, dan sebagainya.<br></br>

                Dalam sistem yang buruk, pekerja kampus sering mengandalkan datangnya satria paningit atau super hero untuk menyelesaikan masalah. Namun, perlu disadari bahwa perubahan tidak terjadi tiba-tiba. Perubahan adalah hal yang tumbuh dan berkembang. Kemerdekaan merupakan kunci dari perubahan. Kemerdekaan adalah benih perubahan, artinya kemerdekaan merupakan fertile source. Regulasi tentang Kampus Merdeka menjadi miris terdengar, karena mengesankan kemerdekaan sebagai pemberian dari pemerintah, dan hanya pemerintah yang dapat memberikan tafsiran tentang bagaimana kampus merdeka.<br>

            <h5 class="card-text text-justify mx-5 lh-sm"><br class="fw-bolder" style="font-weight:bold">Tekanan dan diskriminasi pekerja kampus </h5><br>

            <p class="card-text text-justify mx-5 lh-sm"> Banyak pekerja kampus tidak merasakan nikmatnya kemerdekaan. Diskusi tanggal 16 Nopember 2021 dengan tema Menggagas Serikat Pekerja Kampus, 21 Maret 2022 dengan tema Urgensi Serikat Pekerja di tengah Otoritarianisme, yang diselenggarakan Kaukus Indonesia untuk Kebebasan Akademik memperlihatkan adanya beban tugas yang tinggi, presensi yang ketat, tuntutan jurnal dan outcome dengan berbagai standart, BKD, sister, dan sebagainya, keterampilan dimaknai sebagai hal yang formalitas, akreditasi menjadikan kesibukan bagi pekerja kampus, dibandingkan memproduksi ilmu pengetahuan, melakukan penelitian secara bebas dan membuat masyarakat berdaya. Undang-undang 12 Tahun 2012 Tentang Perguruan Tinggi menyatakan pengaturan, perencanaan, pengawasan, pemantauan, evaluasi pembinaan dan koordinasi dilakukan oleh kementerian. Maka Menterilah yang menentukan baik buruknya dosen. Untuk menjadi dosen yang baik, maka yang dinilai adalah banyaknya publikasi, bukan kehebatannya membuat teori yang berdampak bagi masyarakat. Paparan Prof Mizuno, saat bersolidaritas dalam Kongres Pendirian Serikat Pekerja Kampus tanggal 17 Agustus 2023 di Jakarta.<br></h5>

            <p class="card-text text-justify mx-5 lh-sm">Kondisi yang tidak ideal tersebut, menjadi diskusi-diskusi hangat di KIKA dan berbagai forum dosen sejak 2021, hingga pada puncaknya 19 April 2023 menyatakan menolak Permenpan RB Nomor 1 Tahun 2023.Peraturan tersebut mendapat berbagai kritik, diantaranya, Pertama, PermenPAN-RB ini adalah aksi sepihak kementerian tanpa melalui proses yang partisipatif. Kedua, PermenPAN-RB ini mengatur penilaian kinerja yang secara terang benderang diorientasikan untuk pemenuhan ekspektasi pimpinan. Ketiga, PermenPAN-RB ini hendak mengintegrasikan kinerja dosen ke dalam mesin kerja birokrasi. Pada akhirnya, kreativitas akan dibunuh atas nama institusi. Keempat, beban administratif yang semakin berat. Beban ini akan membuat dosen membangun menara gading yang terasing. Kemudian, tanggal 29 April 2023 dilakukan pernyataan bersama bertajuk “Saya Dosen, Saya Buruh” sebagai bentuk peringatan May day 2023. Hal inilah yang kemudian membuat beberapa pekerja kampus mendeklarasikan dirinya sebagai buruh pada 1 Mei 2023. Aksi demonstrasi yang dimotori serikat pekerja di Universitas Indonesia, KIKA, Universitas Gajah Mada dan berbagai komunitas diskusi kemudian turut membawa animo hingga kemudian menginisiasi kumpulan yang lebih konkrit untuk mengadvokasi hak-hak pekerja kampus menuju keadilan sosial.<br></br>

            <h5 class="card-text text-justify mx-5 lh-sm"> Kemerdekaan Itu Tidak Turun Dari Langit, Tapi Muncul Lewat Kesadaran Kolektif</h5><br>

            <p class="card-text text-justify mx-5 lh-sm">Sejak 1 Mei 2023, pergerakan pekerja kampus semakin masif. Berbagai grup dibuat untuk melakukan pembagian kerja secara efektif. Pembagian kerja yang dilakukan oleh Komite Persiapan Serikat Pekerja Kampus yang diketuai oleh Herdiansyah Hamzah dan Kanti Pertiwi membuat strategi bersama untuk merumuskan hal-hal substansial tentang desain ideal serikat yang akan dibentuk. Hal yang mempertemukan banyak elemen pekerja kampus pada saat itu adalah kesadaran bahwa terdapat sistem yang unfair dan diskriminatif dalam ekosistem kampus yang menyebabkan pekerja kampus tidak dapat mengembangkan diri secara optimal.<br></br>

                Berbagai diskusi digelar, untuk belajar cara-cara berserikat di negara-negara lainnya, baik cara-cara berserikat di benua Australia hingga benua Eropa. “Kebebasan akademik menghadapi ancaman di berbagai tempat di dunia. Akademisi dan mahasiswa menghadapi ancaman persekusi dan hukuman disiplin karena menyebarkan gagasan dan mengajukan pertanyaan. Pemerintah menarik pendanaan pendidikan untuk alasan politis dan semakin sulit bagi akademisi untuk mempertahankan pekerjaan tetap. Kami melihat ini di mana-mana: Afghanistan, Brazil, China, Hungaria, Nikaragua, Amerika Serikat, Venezuela,” kata Daniel Munir dari Scholars at Risk. Scholar At Risk memperhatikan situasi kebebasan akademik di Indonesia, dan melaporkannya dalam Universal Periodic Review Tahun 2022.<br></br>

                Namun, melakukan comparative study dengan negara lain ini dibaurkan dengan situasi dalam negeri. Beberapa komunikasi dilakukan untuk mengumpulkan balung misah serikat pekerja. Serikat yang terbentuk misalnya Serikat Pekerja UI, Sindikasi,Koperja, IKDT Mercubuana, Serikat pekerja UP 45 Yogyakarta menjadi pembanding tantangan situasi pembuatan serikat pekerja kampus. TIm lainnya dalam komite persiapan, melakukan riset pemetaan situasi tuntutan dan masalah pekerja kampus. Tuntutan dan masalah ini kemudian diformulasikan untuk peningkatan kapasitas internal yang telah disusun oleh tim lainnya.<br></br>

                Persiapan pendirian Serikat Pekerja Kampus kemudian membentuk Panitia Kongres Pendirian Serikat Pekerja Kampus yang diketuai Estu Putri Wilujeng. Di sela-sela panitia mempersiapkan hal-hal teknis,anggota sibuk membahas tentang Anggaran Dasar dan Anggaran Rumah Tangga. Perdebatan empat kali pra kongres tanggal 22 Juni, 28 Juni, 6 Juli dan 10 Juli 2023 dengan durasi pembahasan 7-8 jam tiap tanggal dan akhirnya menghasilkan 44 (empat puluh empat) lembar yang menjadi desain Serikat Pekerja Kampus, yang kemudian dirapikan oleh Tim hukum Serikat Pekerja Kampus.<br></br>

                Alhasil, Kongres Pendirian Serikat Pekerja Kampus terselenggara 17 Agustus 2023. Serikat Pekerja Kampus, tumbuh dan berkembang bersama, menggagas kesejahteraan untuk sesama, memaknai dalam keadilan sosial dengan kerja sama. Serikat Pekerja Kampus memiliki prinsip kesetaraan dan non diskriminasi, berdaulat, independen dan demokratis. Prinsip ideal yang dirumuskan, akibat kondisi antitesis yang dialami para pekerja kampus.<br></br>
            </p>
            <a href="<?= base_url('user/formulir') ?>" class="btn btn-success">Mendaftar Serikat</a>
        </div>
    </div>


</div>
<!-- /.container-fluid -->

</div>
<!-- End of Main Content -->